package my.com.avira;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import my.com.avira.Record;
import my.com.avira.Photo;

import my.com.avira.RecordDao;
import my.com.avira.PhotoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordDaoConfig;
    private final DaoConfig photoDaoConfig;

    private final RecordDao recordDao;
    private final PhotoDao photoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        recordDao = new RecordDao(recordDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);

        registerDao(Record.class, recordDao);
        registerDao(Photo.class, photoDao);
    }
    
    public void clear() {
        recordDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

}
