package my.com.avira;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE_ITEM.
 */
public class ImageItem {

    private Long id;
    private Integer article_id;
    private String title;
    private String description;
    private java.util.Date date;

    public ImageItem() {
    }

    public ImageItem(Long id) {
        this.id = id;
    }

    public ImageItem(Long id, Integer article_id, String title, String description, java.util.Date date) {
        this.id = id;
        this.article_id = article_id;
        this.title = title;
        this.description = description;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArticle_id() {
        return article_id;
    }

    public void setArticle_id(Integer article_id) {
        this.article_id = article_id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
