package my.com.avira;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private Long id;
    private Integer record_id;
    private String description;
    private String date_time;
    private Long created_at;
    private Long updated_at;
    private String photos;
    private java.util.Date date;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, Integer record_id, String description, String date_time, Long created_at, Long updated_at, String photos, java.util.Date date) {
        this.id = id;
        this.record_id = record_id;
        this.description = description;
        this.date_time = date_time;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.photos = photos;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRecord_id() {
        return record_id;
    }

    public void setRecord_id(Integer record_id) {
        this.record_id = record_id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDate_time() {
        return date_time;
    }

    public void setDate_time(String date_time) {
        this.date_time = date_time;
    }

    public Long getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Long created_at) {
        this.created_at = created_at;
    }

    public Long getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Long updated_at) {
        this.updated_at = updated_at;
    }

    public String getPhotos() {
        return photos;
    }

    public void setPhotos(String photos) {
        this.photos = photos;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
